# -*- coding: utf-8 -*-
# vim: set ft=python ts=4 sw=4 expandtab:

# Note: this is boilerplate code generated by supybot-plugin-create

from supybot import conf

# from supybot import conf, registry
# from supybot.questions import anything, expect, something, yn

try:
    from supybot.i18n import PluginInternationalization

    _ = PluginInternationalization("Meetbot")
except (ImportError, ModuleNotFoundError):
    _ = lambda x: x  # Run the plugin on a bot without the il8n module

# pylint: disable=unused-argument:
def configure(advanced):  # type: ignore
    # This will be called by supybot to configure this module.  advanced is
    # a bool that specifies whether the user identified themself as an advanced
    # user or not.  You should effect your configuration by manipulating the
    # registry as appropriate.

    conf.registerPlugin("Meetbot", True)


Meetbot = conf.registerPlugin("Meetbot")
# This is where your configuration variables (if any) should go.  For example:
# conf.registerGlobalValue(Meetbot, 'someConfigVariableName',
#     registry.Boolean(False, _("""Help for someConfigVariableName.""")))
