# -*- coding: utf-8 -*-
# vim: set ft=python ts=4 sw=4 expandtab:
# pylint: disable=too-many-ancestors:

# Note: this is boilerplate code generated by supybot-plugin-create

from supybot import callbacks

# from supybot import callbacks, ircutils, plugins, utils
# from supybot.commands import *

try:
    from supybot.i18n import PluginInternationalization

    _ = PluginInternationalization("Meetbot")
except ImportError:
    # Placeholder that allows to run the plugin on a bot
    # without the i18n module
    _ = lambda x: x


class Meetbot(callbacks.Plugin):  # type: ignore
    """Plugin for Limnoria to help run IRC meetings"""

    pass  # pylint: disable=unnecessary-pass:


Class = Meetbot
