# -*- coding: utf-8 -*-
# vim: set ft=python ts=4 sw=4 expandtab:
# pylint: disable=invalid-name: #  the module name must match the plugin name for Limnoria to work

# Note: this is boilerplate code originally generated by supybot-plugin-create

"""
HcoopMeetbot: Plugin for Limnoria to help run IRC meetings
"""
from importlib import reload
from typing import Any, Dict

from supybot import Author, world

from . import config, plugin

__version__ = "0.1.0"
__author__ = Author(name="Kenneth J. Pronovici", email="pronovic@ieee.org")
__contributors__ = {}  # type: Dict[Any, Any]
__url__ = "https://pypi.org/project/hcoop-meetbot/"

reload(config)
reload(plugin)

if world.testing:
    from . import test

Class = plugin.Class
configure = config.configure
