# -*- coding: utf-8 -*-
# vim: set ft=python ts=4 sw=4 expandtab:
# pylint: disable=unused-argument:

# Note: this is boilerplate code originally generated by supybot-plugin-create

import supybot.registry as registry
from supybot import conf

# noinspection PyBroadException
try:
    from supybot.i18n import PluginInternationalization

    _ = PluginInternationalization("HcoopMeetbot")
except:  # pylint: disable=bare-except:
    _ = lambda x: x


def configure(advanced):
    conf.registerPlugin("HcoopMeetbot", True)


hcoopMeetbot = conf.registerPlugin("HcoopMeetbot")
conf.registerGlobalValue(
    hcoopMeetbot, "enableSupybotBasedConfig", registry.Boolean(False, "Enable configuration via the supybot config mechanism.")
)
