# -*- coding: utf-8 -*-
# vim: set ft=python ts=4 sw=4 expandtab:

# Note: this is boilerplate code generated by supybot-plugin-create

# Unfortunately, tests must live alongside the source code for supybot-test to execute them.
# So, this lives here rather than in the tests modules with all of the other unit tests.

# TODO: either remove this or turn it into something useful

from supybot.test import PluginTestCase


class HcoopMeetbotTestCase(PluginTestCase):  # type: ignore
    plugins = ("HcoopMeetbot",)

    # def test_random(self) -> None:
    #     # difficult to test, let's just make sure it works
    #     self.assertNotError("random")
